spring.application.name=e-commerce

server.port=${PORT:8080}


spring.datasource.url=jdbc:mysql://mysql:3306/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


product.profile.image.path=images/


logging.level.org.springframework.security=DEBUG
logging.level.com.zaxxer.hikari=DEBUG


spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600